/**
 * RagAdviceCard Component
 * Displays AI-powered agricultural advice from RAG system
 */

import React, { useState } from 'react';

const RagAdviceCard = ({ advice }) => {
  const [isExpanded, setIsExpanded] = useState(false);

  if (!advice) return null;

  // Limit text if very long
  const maxPreviewLength = 300;
  const isLong = advice.length > maxPreviewLength;
  const displayText = isExpanded ? advice : advice.substring(0, maxPreviewLength);

  return (
    <div className="bg-gradient-to-br from-purple-50 to-indigo-50 rounded-lg p-6 border border-purple-200 shadow-lg hover:shadow-xl transition transform hover:scale-105">
      <div className="flex gap-4">
        <div className="text-4xl">🤖</div>
        <div className="flex-1">
          <h3 className="font-bold text-purple-900 mb-3">AI-Powered Agricultural Guidance</h3>

          <div className="text-gray-800 text-sm leading-relaxed space-y-2 whitespace-pre-wrap">
            {displayText}
            {!isExpanded && isLong && <span className="text-purple-600">...</span>}
          </div>

          {isLong && (
            <button
              onClick={() => setIsExpanded(!isExpanded)}
              className="mt-3 text-purple-600 font-semibold text-sm hover:text-purple-800 transition"
            >
              {isExpanded ? '← Show Less' : 'Show More →'}
            </button>
          )}

          <div className="mt-4 p-3 bg-white bg-opacity-80 backdrop-blur-sm rounded border border-purple-200">
            <p className="text-xs text-gray-600">
              💡 <strong>Tip:</strong> This advice is generated by analyzing agricultural knowledge combined with
              current weather conditions. Always validate recommendations with local farming experts.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default RagAdviceCard;
